{% set name = "pytest-notebook" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "efb9db25c6a823d318edef09fa2a827aaabc1363e588479c4d6136d5411bfa1d"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - attrs
    - black
    - importlib_resources
    - jsonschema
    - jupyter_client
    - nbconvert
    - nbdime
    - nbformat
    - pytest >=3.5.0
    - python >=3.5

test:
  imports:
    - pytest_notebook
    - pytest_notebook.diffing
    - pytest_notebook.example_nbs
    - pytest_notebook.execution
    - pytest_notebook.ipy_magic
    - pytest_notebook.nb_regression
    - pytest_notebook.notebook
    - pytest_notebook.plugin
    - pytest_notebook.post_processors
    - pytest_notebook.resources
    - pytest_notebook.utils
  commands:
    - pytest -h

about:
  home: "https://github.com/chrisjsewell/pytest-notebook"
  license: "BSD"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A pytest plugin for testing Jupyter Notebooks"
  doc_url: "https://pytest-notebook.readthedocs.io"

extra:
  recipe-maintainers:
    - chrisjsewell
