travis:
  secure:
    BINSTAR_TOKEN: sppzV+KtvcJUQKiRn34tJeApA/SlUq0i85xf15/Iq5CW6ilETpu763n2LTVSrMNqeJFDd1gpxKl/FSUT+rq8nk8IYTpLkb/86/hW779EBKDGbzGgo3lSXBxkxIoi11yTABEj35OIKUnA82lir4LDSIukZPvdK0zFB04VAut641L5LaDrym7GZ5WXkEyFJGK9k+V7UXpP0aucTeuMmzflT7lHsvf9c6HXp2igyaIE/rS9IHUBteGvR0npmPdV89hWP4OCDhUyRN7+0sJojTDUf6neFVHfdP9hFpX2yummBV0th/oNYAEFK0FxDgn1macNFgbbuiuHUE7CzqAceXUqWMccynSz92aAJZFBllgOgRPujl5llSiiUsS1jHWTBdbm/n4vvBWGlnoL+b26gByP9dhd5CStmWpRNCtE8gDMajNC96lKvGldtSY1zS/TUI84PwB1GCAHLDfPukujia2kwfpRQWJCJ/skMSLnNU/RRc3ls1nK0l6YWTYII56PLnK364V5OhVFiJxV5E94xv4hbKSXHHKvNNTd0VBdXHmAz4+L2yp4ZCmN7e584kiCoXMaWY1io7jny77LpteX5uwXg4TQE6V84cv1MKK8TWjA6jgSAi7bTFZsBdA8/1eZDCun0lOOgs4PAqDYCfXhjVcC/xFujLfT0CG7o72B9X52NhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
